FROM postgres:14
# RUN apt-get update
# RUN apt-get install -y postgresql postgresql-contrib

# VOLUME /var/lib/postgresql/data

# EXPOSE 5432
# ENTRYPOINT psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE gutendex TO postgres;'
